CREATE TABLE USERA (
    USE_ID INT PRIMARY KEY AUTO_INCREMENT,
    USE_NOM varchar(50),
    USE_PRENOM varchar(50),
    USE_EMAIL varchar(50),
    USE_MDP varchar(50),
    USE_TELEPHONE varchar(50)
);

CREATE TABLE RESTAURANT (
    RES_ID INT PRIMARY KEY AUTO_INCREMENT,
    RES_TYPE varchar(50),
    RES_NOM varchar(50)
);

CREATE TABLE AVIS (
    AVI_IDU INT,
    AVI_IDR INT,
    AVI_NOTE INT,
    AVI_CRITIQUE varchar(2048),
    CONSTRAINT PRIMARY KEY (AVI_IDU, AVI_IDR),
    FOREIGN KEY (AVI_IDU) REFERENCES USERA(USE_ID) ON DELETE CASCADE,
    FOREIGN KEY (AVI_IDR) REFERENCES RESTAURANT(RES_ID) ON DELETE CASCADE
);